# Generated by Django 4.0.1 on 2022-02-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_todo_description_alter_todo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.CharField(blank=None, max_length=250, verbose_name='Описания'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(blank=None, max_length=40, verbose_name='Называния'),
        ),
    ]
